version: '3.8'

services:
  web:
    image: django:latest
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./my_django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:password@db:5432/pgdb
      - SECRET_KEY=mysecretkey

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database:/database
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: